import type { ReactNode } from 'react';
import type { Project, CalendarEvent, EmailTemplate, SmartAnswer } from '../types';
import { REFERENCE_DOCS } from '../data/referenceDocs';

function escapeRegex(str: string): string {
  return str.replace(/[-\\^$*+?.()|[\]{}]/g, '\\$&');
}

// ─── Google Calendar URL Generator ──────────────────────────────────────────

export const getGoogleCalendarUrl = (project: Project): string => {
  if (!project.goLiveDate) return '';
  const cleanDate = project.goLiveDate.replace(/-/g, '');
  const start = `${cleanDate}T090000`;
  const end = `${cleanDate}T100000`;
  const title = encodeURIComponent(`[SignalFlow] Go-Live: ${project.name} (${project.number})`);
  const details = encodeURIComponent(
    `Project: ${project.name}\n` +
    `Project Number: ${project.number}\n` +
    `Type: ${project.type}\n` +
    `Location: ${project.city}, ${project.state}\n` +
    `PM: ${project.pm.name}\n` +
    `AE: ${project.ae.name}\n\n` +
    `Generated by SignalFlow PWA.`
  );
  const location = encodeURIComponent(`${project.city}, ${project.state}`);
  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${start}/${end}&details=${details}&location=${location}`;
};

// ─── ICS File Download ──────────────────────────────────────────────────────

export const downloadIcsFile = (project: Project, onToast: (msg: string) => void) => {
  if (!project.goLiveDate) return;
  const cleanDate = project.goLiveDate.replace(/-/g, '');
  const start = `${cleanDate}T090000`;
  const end = `${cleanDate}T100000`;
  const nowStr = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

  const icsLines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SignalFlow//Hospital Wireless Deployment//EN',
    'BEGIN:VEVENT',
    `UID:${project.id}@signalflow.pwa`,
    `DTSTAMP:${nowStr}`,
    `DTSTART:${start}`,
    `DTEND:${end}`,
    `SUMMARY:[SignalFlow] Go-Live: ${project.name} (${project.number})`,
    `DESCRIPTION:Project Number: ${project.number}\\nType: ${project.type}\\nLocation: ${project.city}\\, ${project.state}\\nPM: ${project.pm.name}\\nAE: ${project.ae.name}\\n\\nGenerated via SignalFlow PWA.`,
    `LOCATION:${project.city}\\, ${project.state}`,
    'END:VEVENT',
    'END:VCALENDAR',
  ];

  const blob = new Blob([icsLines.join('\r\n')], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${project.number}_GoLive.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
  onToast('Outlook / iCal event file downloaded!');
};

// ─── Mailto URL Generator ───────────────────────────────────────────────────

export const getMailtoUrl = (temp: { to?: string; cc?: string; subject: string; body: string }): string => {
  const to = encodeURIComponent(temp.to || '');
  const cc = encodeURIComponent(temp.cc || '');
  const subject = encodeURIComponent(temp.subject || '');
  const body = encodeURIComponent(temp.body || '');
  return `mailto:${to}?cc=${cc}&subject=${subject}&body=${body}`;
};

// ─── Google Drive Folder Structure ──────────────────────────────────────────

export const DRIVE_FOLDER_STRUCTURE = `📁 [Project Number] Project Name/
├── 📂 01_Floor_Plans/     (AutoCAD DWGs, PDFs)
├── 📂 02_Ekahau_Files/    (.esx projects, surveys)
├── 📂 03_Site_Photos/     (AP placement proofs)
└── 📂 04_Final_Reports/   (Completed PDF exports)`;

export const buildDriveStructureText = (project: Project | null): string =>
  DRIVE_FOLDER_STRUCTURE
    .replace('[Project Number]', project?.number || 'XXXX')
    .replace('Project Name', project?.name || 'Project');

// ─── Smart Answer Search ────────────────────────────────────────────────────

export const findSmartAnswer = (query: string): SmartAnswer | null => {
  if (!query || query.trim().length < 3) return null;

  const tokens = query.toLowerCase()
    .replace(/[?.!,;]/g, '')
    .split(/\s+/)
    .filter(t => t.length > 2);

  if (tokens.length === 0) return null;

  let bestSection: any = null;
  let bestDoc: any = null;
  let bestScore = 0;

  for (const doc of REFERENCE_DOCS) {
    for (const sec of doc.sections) {
      let score = 0;

      for (const token of tokens) {
        if (sec.keywords.some(k => k.toLowerCase().includes(token))) {
          score += 15;
        }
      }

      const contentLower = sec.content.toLowerCase();
      for (const token of tokens) {
        let idx = -1;
        while ((idx = contentLower.indexOf(token, idx + 1)) !== -1) {
          score += 3;
        }
      }

      const titleLower = sec.title.toLowerCase();
      for (const token of tokens) {
        if (titleLower.includes(token)) {
          score += 8;
        }
      }

      if (score > bestScore) {
        bestScore = score;
        bestSection = sec;
        bestDoc = doc;
      }
    }
  }

  if (bestScore >= 5 && bestSection && bestDoc) {
    return {
      title: bestDoc.title,
      docNum: bestDoc.docNum,
      category: bestDoc.category,
      sectionTitle: bestSection.title,
      excerpt: bestSection.content,
      score: bestScore,
    };
  }

  return null;
};

// ─── Highlight Text ─────────────────────────────────────────────────────────

export const highlightText = (text: string, query: string): ReactNode => {
  if (!query || query.trim().length < 3) return <span>{text}</span>;

  const tokens = query
    .toLowerCase()
    .replace(/[?.!,;]/g, '')
    .split(/\s+/)
    .filter(t => t.length > 2);

  if (tokens.length === 0) return <span>{text}</span>;

  const pattern = tokens.map(t => escapeRegex(t)).join('|');
  const regex = new RegExp(`(${pattern})`, 'gi');

  const parts = text.split(regex);

  return (
    <span>
      {parts.map((part, i) => {
        const isMatch = tokens.some(
          t => part.toLowerCase() === t.toLowerCase() ||
               (part.toLowerCase().includes(t.toLowerCase()) && t.length > 3)
        );
        return isMatch ? (
          <mark key={i} className="bg-sunset-500/30 text-sunset-400 px-0.5 rounded font-bold">
            {part}
          </mark>
        ) : (
          part
        );
      })}
    </span>
  );
};

// ─── Stage Progression ──────────────────────────────────────────────────────

export const STAGE_ORDER: Project['stage'][] = [
  'Kickoff', 'Pre-Work', 'On-Site', 'Reporting', 'Completed',
];

export const computeStageFromChecklist = (
  completedCount: number,
  totalCount: number,
  type: Project['type'],
): Project['stage'] => {
  const pct = completedCount / totalCount;

  if (type === 'Wireless Assessment') {
    if (pct < 0.25) return 'Kickoff';
    if (pct < 0.6) return 'Pre-Work';
    if (pct < 0.8) return 'On-Site';
    if (pct < 0.95) return 'Reporting';
    return 'Completed';
  }

  // Wireless Design
  if (pct < 0.2) return 'Kickoff';
  if (pct < 0.5) return 'Pre-Work';
  if (pct < 0.8) return 'On-Site';
  if (pct < 0.95) return 'Reporting';
  return 'Completed';
};

// ─── Calendar Events Generator ──────────────────────────────────────────────

export const getCalendarEvents = (projects: Project[]): CalendarEvent[] => {
  const events: CalendarEvent[] = [];
  projects.forEach(p => {
    if (p.travelStart && p.travelEnd) {
      let curr = new Date(p.travelStart);
      const end = new Date(p.travelEnd);
      while (curr <= end) {
        events.push({
          date: curr.toISOString().split('T')[0],
          type: 'travel',
          name: `${p.name} (Travel)`,
        });
        curr.setDate(curr.getDate() + 1);
      }
    }
    if (p.siteStart && p.siteEnd) {
      let curr = new Date(p.siteStart);
      const end = new Date(p.siteEnd);
      while (curr <= end) {
        events.push({
          date: curr.toISOString().split('T')[0],
          type: 'site',
          name: `${p.name} (On-Site)`,
        });
        curr.setDate(curr.getDate() + 1);
      }
    }
    if (p.goLiveDate) {
      events.push({
        date: p.goLiveDate,
        type: 'golive',
        name: `${p.name} [GO-LIVE]`,
      });
    }
  });
  return events;
};

// ─── Email Templates Generator ──────────────────────────────────────────────

export const getEmailTemplates = (project: Project): EmailTemplate[] => [
  {
    id: 'temp1',
    title: '📧 Kickoff Floorplan Request',
    desc: 'Request raw AutoCAD/DWG files and marked-up PDF drawings of coverage wings.',
    to: '',
    cc: '',
    subject: `NK ${project.type} Kickoff Docs - ${project.name} (${project.number})`,
    body: `Hi Team,\n\nWe are gearing up for the ${project.type === 'Wireless Assessment' ? 'wireless assessment' : 'wireless design'} for ${project.name} (Project: ${project.number}). To prepare our predictive layout and calibrate our Ekahau Sidekick devices, I will need the hospital's latest floorplans.\n\nSpecifically, could you request from the hospital contacts:\n1. Clean CAD/DWG floorplans of the coverage areas (without structural lines cleaned out if possible).\n2. A marked-up PDF highlighting the exact physical departments/units where telemetry coverage is required (e.g., ICU, Cardiac Stepdown, etc.).\n\nHaving these files early will ensure we arrive fully prepared and keep our on-site survey walks precise.\n\nThank you,\nCharles Phifer\nWireless Network Engineer, Nihon Kohden`,
  },
  {
    id: 'temp2',
    title: '📋 Pre-Visit Hospital Checklist',
    desc: 'Sent to the Hospital IT/BioMed contacts prior to arriving to ensure POC hardware is ready.',
    to: `${project.itContact.email}`,
    cc: '',
    subject: `Preparing for your Nihon Kohden Site Visit - ${project.name}`,
    body: `Dear ${project.itContact.name},\n\nI am looking forward to our upcoming site ${project.type === 'Wireless Assessment' ? 'assessment' : 'design visit'} on ${project.siteStart}. To ensure our proof-of-concept (POC) telemetry testing goes smoothly, please verify the following items are prepared prior to my arrival:\n\n1. Active Network SSID: Ensure the custom telemetry SSID is active on the hospital network in our target testing areas.\n2. Telemetry Server VM: Verify the virtual machine running the central station server is initialized and accessible.\n3. Security Clearance/Badges: Confirm I will be able to obtain visitor credentialing badges (${project.credentials}) upon my arrival in the lobby.\n\nIf we have any outstanding technical issues with the SSID configuration, let's schedule a 15-minute alignment call before the travel dates.\n\nBest regards,\nCharles Phifer\nWireless Network Engineer, Nihon Kohden`,
  },
  {
    id: 'temp3',
    title: '📑 Technical Report Review Request',
    desc: 'Drafted once report is done, asking the PM to schedule the customer review call.',
    to: '',
    cc: '',
    subject: `${project.type} Report Draft Completed - ${project.name} (${project.number})`,
    body: `Hi ${project.pm.name},\n\nI have completed the technical ${project.type === 'Wireless Assessment' ? 'wireless assessment' : 'wireless design'} report and successfully uploaded the final PDF to Salesforce for ${project.name}.\n\nThe survey indicates excellent coverage options with the current design, and our telemetry proof-of-concept walked flawlessly. I have outlined our final recommendations on AP configurations and channel allocations in the document.\n\nCould you please schedule a 30-minute review call with the hospital's IT and BioMed teams so we can walk through our findings and finalize our sign-off?\n\nI have uploaded the working files to our SignalFlow Google Drive folder.\n\nBest,\nCharles Phifer\nWireless Network Engineer, Nihon Kohden`,
  },
];

// ─── Default Wizard Values ──────────────────────────────────────────────────

export const DEFAULT_WIZARD_STATE = {
  wizPmName: 'Sarah Jenkins',
  wizAeName: 'Marcus Vance',
  wizState: 'TN',
  wizCredentials: 'Symplr',
  wizDrive: true,
  wizCalendar: true,
} as const;

export const CREDENTIAL_OPTIONS = [
  { value: 'Symplr (Required)', label: 'Symplr' },
  { value: 'Reptrax (Required)', label: 'Reptrax' },
  { value: 'IntelliCentrics', label: 'IntelliCentrics' },
  { value: 'None / General check-in', label: 'None / Regular Visitor' },
] as const;